### ISSUE TITLE
Project Info overhaul

### ISSUE THREAD

**Issue by aitikgupta** [Open-Sourced-Olaf/vscode-github-projects#20]
Lot of things in ProjectInfo.svelte. Firstly, making it look like a  card. (Since @SamuelY is working on drag and drop, he might make it look like a card too), but other than one should know if that card is a card or a linked issue. (if you check out how GitHub differentiates a card and a linked issue, you'll know what I'm talking about).
Also things like hamburger sign, so that we could see options like Delete card, Edit Card (which will open up a popup asking for input), add card on the top of the card, etc)

**Comment by YuanSamuel** [comment]
Closed by #16 and #26 along with various others
