### ISSUE TITLE
Create Models

### ISSUE THREAD

**Issue by YuanSamuel** [Open-Sourced-Olaf/vscode-github-projects#8]

**Comment by aitikgupta** [comment]
Data Model:
![Untitled Document (1)](https://user-images.githubusercontent.com/43996118/108566899-2c5dcf00-732d-11eb-8782-7862b3e3a32b.png)

Architecture:
![Untitled Document](https://user-images.githubusercontent.com/43996118/108566810-06d0c580-732d-11eb-9d06-44023673c0db.png)
